export const quotes = [
  {
    q: "It's the unknown we fear when we look upon death and darkness, nothing more.",
    a: "Albus Dumbledore",
    c: "76",
    h: "<blockquote>&ldquo;It's the unknown we fear when we look upon death and darkness, nothing more.&rdquo; &mdash; <footer>Albus Dumbledore</footer></blockquote>",
  },
  {
    q: "Being spiritual has nothing to do with what you believe and everything to do with your state of consciousness.",
    a: "Eckhart Tolle",
    c: "110",
    h: "<blockquote>&ldquo;Being spiritual has nothing to do with what you believe and everything to do with your state of consciousness.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "Change happens when the pain of holding on becomes greater than the fear of letting go.",
    a: "Spencer Johnson",
    c: "87",
    h: "<blockquote>&ldquo;Change happens when the pain of holding on becomes greater than the fear of letting go.&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "Don't look back - you're not going that way.",
    a: "Mary Engelbreit",
    c: "44",
    h: "<blockquote>&ldquo;Don't look back - you're not going that way.&rdquo; &mdash; <footer>Mary Engelbreit</footer></blockquote>",
  },
  {
    q: "It is useless to meet revenge with revenge; it will heal nothing.",
    a: "J.R.R. Tolkien",
    c: "65",
    h: "<blockquote>&ldquo;It is useless to meet revenge with revenge; it will heal nothing.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
  },
  {
    q: "We become brave by doing brave acts.",
    a: "Aristotle",
    c: "36",
    h: "<blockquote>&ldquo;We become brave by doing brave acts.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "The only difference between success and failure is the ability to take action.",
    a: "Alexander Graham Bell",
    c: "78",
    h: "<blockquote>&ldquo;The only difference between success and failure is the ability to take action.&rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
  },
  {
    q: "If you're really truthful with yourself, it's a wonderful guidance.  ",
    a: "Charlie Chaplin",
    c: "69",
    h: "<blockquote>&ldquo;If you're really truthful with yourself, it's a wonderful guidance.  &rdquo; &mdash; <footer>Charlie Chaplin</footer></blockquote>",
  },
  {
    q: "Nothing is easier than fault finding.",
    a: "Og Mandino",
    c: "37",
    h: "<blockquote>&ldquo;Nothing is easier than fault finding.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Try not to become a man of success, but rather try to become a man of value.",
    a: "Albert Einstein",
    c: "76",
    h: "<blockquote>&ldquo;Try not to become a man of success, but rather try to become a man of value.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "As you think, so shall you become. ",
    a: "Bruce Lee",
    c: "35",
    h: "<blockquote>&ldquo;As you think, so shall you become. &rdquo; &mdash; <footer>Bruce Lee</footer></blockquote>",
  },
  {
    q: "What would life be if we had no courage to attempt anything? ",
    a: "Vincent van Gogh",
    c: "61",
    h: "<blockquote>&ldquo;What would life be if we had no courage to attempt anything? &rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "What do we live for, if it is not to make life less difficult for each other?",
    a: "George Eliot",
    c: "77",
    h: "<blockquote>&ldquo;What do we live for, if it is not to make life less difficult for each other?&rdquo; &mdash; <footer>George Eliot</footer></blockquote>",
  },
  {
    q: "Progress is limited by your ability to change your mind.",
    a: "Jack Butcher",
    c: "56",
    h: "<blockquote>&ldquo;Progress is limited by your ability to change your mind.&rdquo; &mdash; <footer>Jack Butcher</footer></blockquote>",
  },
  {
    q: "It is in your moments of decision that your destiny is shaped.",
    a: "Tony Robbins",
    c: "62",
    h: "<blockquote>&ldquo;It is in your moments of decision that your destiny is shaped.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "You can't get to a place that you don't believe exists.",
    a: "Unknown",
    c: "55",
    h: "<blockquote>&ldquo;You can't get to a place that you don't believe exists.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "It's not how much money you make, it's how much money you keep.",
    a: "Robert Kiyosaki",
    c: "63",
    h: "<blockquote>&ldquo;It's not how much money you make, it's how much money you keep.&rdquo; &mdash; <footer>Robert Kiyosaki</footer></blockquote>",
  },
  {
    q: "The essence of the Way is detachment.",
    a: "Bodhidharma",
    c: "37",
    h: "<blockquote>&ldquo;The essence of the Way is detachment.&rdquo; &mdash; <footer>Bodhidharma</footer></blockquote>",
  },
  {
    q: "If you want something new, you have to stop doing something old.",
    a: "Peter Drucker",
    c: "64",
    h: "<blockquote>&ldquo;If you want something new, you have to stop doing something old.&rdquo; &mdash; <footer>Peter Drucker</footer></blockquote>",
  },
  {
    q: "If light is in your heart, you will find your way home.  ",
    a: "Rumi",
    c: "57",
    h: "<blockquote>&ldquo;If light is in your heart, you will find your way home.  &rdquo; &mdash; <footer>Rumi</footer></blockquote>",
  },
  {
    q: "If you read a lot of books, you're considered well-read. But if you watch a lot of TV, you're not considered well-viewed.",
    a: "Lily Tomlin",
    c: "121",
    h: "<blockquote>&ldquo;If you read a lot of books, you're considered well-read. But if you watch a lot of TV, you're not considered well-viewed.&rdquo; &mdash; <footer>Lily Tomlin</footer></blockquote>",
  },
  {
    q: "Forgive yourself for your faults and your mistakes and move on.",
    a: "Les Brown",
    c: "63",
    h: "<blockquote>&ldquo;Forgive yourself for your faults and your mistakes and move on.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "Just do what must be done. This may not be happiness but it is greatness.",
    a: "George Bernard Shaw",
    c: "73",
    h: "<blockquote>&ldquo;Just do what must be done. This may not be happiness but it is greatness.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
  },
  {
    q: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    a: "Winston Churchill",
    c: "86",
    h: "<blockquote>&ldquo;Success is not final, failure is not fatal: it is the courage to continue that counts.&rdquo; &mdash; <footer>Winston Churchill</footer></blockquote>",
  },
  {
    q: "Discipline is the bridge between goals and accomplishment.",
    a: "Jim Rohn",
    c: "58",
    h: "<blockquote>&ldquo;Discipline is the bridge between goals and accomplishment.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "The only normal people are the ones you don't know very well.",
    a: "Alfred Adler",
    c: "61",
    h: "<blockquote>&ldquo;The only normal people are the ones you don't know very well.&rdquo; &mdash; <footer>Alfred Adler</footer></blockquote>",
  },
  {
    q: "Always be a first rate version of yourself and not a second rate version of someone else.",
    a: "Judy Garland",
    c: "89",
    h: "<blockquote>&ldquo;Always be a first rate version of yourself and not a second rate version of someone else.&rdquo; &mdash; <footer>Judy Garland</footer></blockquote>",
  },
  {
    q: "Beware of false knowledge, it is more dangerous than ignorance.",
    a: "George Bernard Shaw",
    c: "63",
    h: "<blockquote>&ldquo;Beware of false knowledge, it is more dangerous than ignorance.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
  },
  {
    q: "The more we have the less we own.",
    a: "Meister Eckhart",
    c: "33",
    h: "<blockquote>&ldquo;The more we have the less we own.&rdquo; &mdash; <footer>Meister Eckhart</footer></blockquote>",
  },
  {
    q: "If you're afraid to die, you're afraid to live. You can't have one without the other.",
    a: "Rita Mae Brown",
    c: "85",
    h: "<blockquote>&ldquo;If you're afraid to die, you're afraid to live. You can't have one without the other.&rdquo; &mdash; <footer>Rita Mae Brown</footer></blockquote>",
  },
  {
    q: "Men are disturbed not by things, but by the view which they take of them.",
    a: "Epictetus",
    c: "73",
    h: "<blockquote>&ldquo;Men are disturbed not by things, but by the view which they take of them.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "A mistake is only an error, it becomes a mistake when you fail to correct it.",
    a: "John Lennon",
    c: "77",
    h: "<blockquote>&ldquo;A mistake is only an error, it becomes a mistake when you fail to correct it.&rdquo; &mdash; <footer>John Lennon</footer></blockquote>",
  },
  {
    q: "Youth ages, immaturity is outgrown, ignorance can be educated, and drunkenness sobered, but stupid lasts forever.",
    a: "Aristophanes",
    c: "113",
    h: "<blockquote>&ldquo;Youth ages, immaturity is outgrown, ignorance can be educated, and drunkenness sobered, but stupid lasts forever.&rdquo; &mdash; <footer>Aristophanes</footer></blockquote>",
  },
  {
    q: "When you view failure as feedback, you get more done. When you view failure as a finality, you get nothing done.",
    a: "Jack Butcher",
    c: "112",
    h: "<blockquote>&ldquo;When you view failure as feedback, you get more done. When you view failure as a finality, you get nothing done.&rdquo; &mdash; <footer>Jack Butcher</footer></blockquote>",
  },
  {
    q: "No one can compete with you on being you. Most of life is a search for who and what needs you the most.",
    a: "Naval Ravikant",
    c: "103",
    h: "<blockquote>&ldquo;No one can compete with you on being you. Most of life is a search for who and what needs you the most.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
  },
  {
    q: "It is better to learn late than never.",
    a: "Publilius Syrus",
    c: "38",
    h: "<blockquote>&ldquo;It is better to learn late than never.&rdquo; &mdash; <footer>Publilius Syrus</footer></blockquote>",
  },
  {
    q: "Sometimes it is more important to discover what one cannot do, than what one can do.",
    a: "Lin Yutang",
    c: "84",
    h: "<blockquote>&ldquo;Sometimes it is more important to discover what one cannot do, than what one can do.&rdquo; &mdash; <footer>Lin Yutang</footer></blockquote>",
  },
  {
    q: "When you say yes to change, you are choosing to navigate that path peacefully and happily and see where it takes you.",
    a: "Sonia Ricotti",
    c: "117",
    h: "<blockquote>&ldquo;When you say yes to change, you are choosing to navigate that path peacefully and happily and see where it takes you.&rdquo; &mdash; <footer>Sonia Ricotti</footer></blockquote>",
  },
  {
    q: "We are most nearly ourselves when we achieve the seriousness of the child at play.",
    a: "Heraclitus",
    c: "82",
    h: "<blockquote>&ldquo;We are most nearly ourselves when we achieve the seriousness of the child at play.&rdquo; &mdash; <footer>Heraclitus</footer></blockquote>",
  },
  {
    q: "Life is like a wheel. Sooner or later, it always comes around to where you started again.",
    a: "Stephen King",
    c: "89",
    h: "<blockquote>&ldquo;Life is like a wheel. Sooner or later, it always comes around to where you started again.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "Our happiness depends on the habit of mind we cultivate.",
    a: "Norman Vincent Peale",
    c: "56",
    h: "<blockquote>&ldquo;Our happiness depends on the habit of mind we cultivate.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "If we did all the things we are capable of, we would literally astound ourselves.",
    a: "Thomas Edison",
    c: "81",
    h: "<blockquote>&ldquo;If we did all the things we are capable of, we would literally astound ourselves.&rdquo; &mdash; <footer>Thomas Edison</footer></blockquote>",
  },
  {
    q: "Death smiles at us all. All we can do is smile back.",
    a: "Marcus Aurelius",
    c: "52",
    h: "<blockquote>&ldquo;Death smiles at us all. All we can do is smile back.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "Do not wait for leaders; do it alone, person to person.",
    a: "Mother Teresa",
    c: "55",
    h: "<blockquote>&ldquo;Do not wait for leaders; do it alone, person to person.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: "A fool sees himself as another, but a wise man sees others as himself.",
    a: "Dogen",
    c: "70",
    h: "<blockquote>&ldquo;A fool sees himself as another, but a wise man sees others as himself.&rdquo; &mdash; <footer>Dogen</footer></blockquote>",
  },
  {
    q: "Change the changeable, accept the unchangeable, and remove yourself from the unacceptable. ",
    a: "Denis Waitley",
    c: "91",
    h: "<blockquote>&ldquo;Change the changeable, accept the unchangeable, and remove yourself from the unacceptable. &rdquo; &mdash; <footer>Denis Waitley</footer></blockquote>",
  },
  {
    q: "If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month.",
    a: "Theodore Roosevelt",
    c: "109",
    h: "<blockquote>&ldquo;If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month.&rdquo; &mdash; <footer>Theodore Roosevelt</footer></blockquote>",
  },
  {
    q: "Longevity is a fleeting moment that lasts forever.",
    a: "Vidal Sassoon",
    c: "50",
    h: "<blockquote>&ldquo;Longevity is a fleeting moment that lasts forever.&rdquo; &mdash; <footer>Vidal Sassoon</footer></blockquote>",
  },
  {
    q: "Cleverness is not wisdom.",
    a: "Euripides",
    c: "25",
    h: "<blockquote>&ldquo;Cleverness is not wisdom.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
  {
    q: "I was wise enough to never grow up while fooling most people into believing I had. ",
    a: "Margaret Mead",
    c: "83",
    h: "<blockquote>&ldquo;I was wise enough to never grow up while fooling most people into believing I had. &rdquo; &mdash; <footer>Margaret Mead</footer></blockquote>",
  },
];
